# version: "3.5"


# networks:
#   webnet:
#     driver: overlay
#     attachable: true # Needed in order to run custom commands in the container

# services:
#   app:
#     image: milace/curso_elixir_db:0.1.0
#     ports:
#       - "80:4000"
#     env_file:
#       - config/docker.env
#     depends_on:
#       - db
#     deploy:
#       replicas: 1
#       restart_policy:
#         condition: on-failure
#     networks:
#       - webnet

#   db:
#     image: postgres:10-alpine
#     deploy:
#       replicas: 1
#       placement:
#         constraints: [node.role == manager]
#       restart_policy:
#         condition: on-failure
#     volumes:
#       - "./volumes/postgres:/var/lib/postgresql/data"
#     ports:
#       - "5432:5432"
#     env_file:
#       - config/docker.env
#     networks:
#       - webnet

version: '3.8'

services:

  mongo:
    image: mongo:3.4
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example